[added] Bashified

diff --git a/modules/opt13 b/modules/opt13
--- a/modules/opt13
+++ b/modules/opt13
@@ -1,141 +1,136 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-adb devices | sed -n '2,$p' | awk '{ print $1 }' >.temp/dev_list_temp 2>/dev/null
-dev=($(cat .temp/dev_list_temp))
-dev=("${dev[@]}")
-dev_1=$(echo "${dev[0]}")
-dev_2=$(echo "${dev[1]}")
-dev_3=$(echo "${dev[2]}")
+#Total device count setting to zero initially
+total_dev=0
 
-## DEVICE MODEL EXTARCT ##
+## DEVICE ID & MODEL EXTARCT ##
+dev=$(bash modules/HelperFunctions/GetDevices)
 
-adb devices -l | grep model >.temp/dev_list_model_temp 2>/dev/null
-model=($(cat .temp/dev_list_model_temp))
-model=("${model[@]}")
-mod_1=$(echo "${model[4]}" | cut -c 7-)
-mod_2=$(echo "${model[11]}" | cut -c 7-)
-mod_3=$(echo "${model[18]}" | cut -c 7-)
-
-if [ "$dev_1" == "" ]; then
-    total_dev=0
-else
-    total_dev=1
-    if [ "$dev_2" == "" ]; then
-        total_dev=1
-    else
-        total_dev=2
-        if [ "$dev_3" == "" ]; then
-            total_dev=2
-        else
-            total_dev=3
-        fi
-    fi
+if [ "$dev" != "" ]; then
+    total_dev=${#dev[@]}
 fi
 
+
 apk_uninstall() {
-    read -p $'\e[1;93mENTER THE PACKAGE NAME YOU WANT TO UNINSTALL : \e[1;92m' uninstall_pkg
+    devcode=$1
+    modelname=$2
+    
+    read -rp $'\e[1;93mENTER THE PACKAGE NAME YOU WANT TO UNINSTALL : \e[1;92m' uninstall_pkg
     if [ "$uninstall_pkg" == "" ]; then
-        echo -e ""
-        apk_uninstall
+        apk_uninstall "$devcode" "$modelname"
     else
-        adb -s $devv uninstall $uninstall_pkg &>/dev/null
-        if [ "$?" == "0" ]; then
-            echo -e "\n\e[1;92mSuccessfully uninstalled the 'apk' into device $modd\n"
+        
+        if adb -s "$devcode" uninstall "$uninstall_pkg" &>/dev/null; then
+            echo -e "\n\e[1;92mSuccessfully uninstalled the 'apk' into device $modelname\n"
         else
-            echo -e "\n\e[1;91mFailed uninstalling the 'apk' into device $modd\n"
+            echo -e "\n\e[1;91mFailed uninstalling the 'apk' into device $modelname\n"
         fi
     fi
 }
 
-dev_1_uninst() {
-
-    echo -e "\n\e[1;92mUninstalling the 'apk' from device $mod_1\n"
-    devv=$(echo $dev_1)
-    modd=$(echo $mod_1)
-    apk_uninstall
-
-}
-
-dev_2_uninst() {
-
-    echo -e "\n\e[1;92mUninstalling the 'apk' from device $mod_2\n"
-    devv=$(echo $dev_2)
-    modd=$(echo $mod_2)
-    apk_uninstall
-
-}
-
-dev_3_uninst() {
-
-    echo -e "\n\e[1;92mUninstalling the 'apk' from device $mod_3\n"
-    devv=$(echo $dev_3)
-    modd=$(echo $mod_3)
-    apk_uninstall
-
-}
 
 if [ "$total_dev" == "0" ]; then
     echo -e "\e[91;1mNO DEVICE CONNECTED"
 else
     if [ "$total_dev" == "1" ]; then
 
-        dev_1_uninst
+        devcode=$(echo "${dev[0]}" | awk '{print $1}')
+        modelname=$(echo "${dev[0]}" | awk '{print $2}')
+
+        echo -e "\e[93m1. \e[92m$devcode , \e[93mModel : \e[92m$modelname"
+        dev_install "$devcode" "$modelname"
 
     else
-        if [ "$total_dev" == "2" ]; then
-            echo -e "\e[93mSelect the device to Uninstall 'apk' :- \e[92m\n"
-            echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
-            echo -e "\e[93m2. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
-            while [ 1 ]; do
-                read -p $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
-                case $options in
-                "1")
-                    dev_1_uninst
-                    break
-                    ;;
-                "2")
-                    dev_2_uninst
-                    break
-                    ;;
-                *) echo -e "\n\e[1;4;91mENTER THE RIGHT OPTION BRO :- (1/2)\n" ;;
-                esac
-            done
-        else
-            if [ "$total_dev" == "3" ]; then
-                echo -e "\e[93mSelect the device to Uninstall 'apk' :- \e[92m\n"
-                echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
-                echo -e "\e[93m1. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
-                echo -e "\e[93m1. \e[92m$dev_3 , \e[93mModel : \e[92m$mod_3"
-                while [ 1 ]; do
-                    read -p $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
-                    case $options in
-                    "1")
-                        dev_1_uninst
-                        break
-                        ;;
-                    "2")
-                        dev_2_uninst
-                        break
-                        ;;
-                    "3")
-                        dev_3_uninst
-                        break
-                        ;;
-                    *) echo -e "\n\e[1;4;91mENTER THE RIGHT OPTION BRO :- (1/2/3/)\n" ;;
-                    esac
-                done
+
+        echo -e "\e[93mSelect the device to Uninstall 'apk' :- \e[92m\n"
+
+        for ((i = 0; i < total_dev; i++)); do
+            devcode=$(echo "${dev[$i]}" | awk '{print $1}')
+            modelname=$(echo "${dev[$i]}" | awk '{print $2}')
+            echo -e "\e[93m1. \e[92m $devcode, \e[93mModel : \e[92m$modelname "
+        done
+
+        while true; do
+
+            read -rp $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
+            [[ $options =~ ^[0-9]+$ ]] || {
+                echo -e "\e[93m\nEnter a valid number"
+                continue
+            }
+            if ((options >= 1 && options <= total_dev)); then
+
+                devcode=$(echo "${dev[$options - 1]}" | awk '{print $1}')
+                modelname=$(echo "${dev[$options - 1]}" | awk '{print $2}')
+
+                apk_uninstall "$devcode" "$modelname"
+
+                break
+
+            else
+                echo -e "\e[93m\nEnter a valid number"
             fi
-        fi
+
+        done
 
     fi
 fi
 
-read -p $'\n\e[93;1mDo you want to clear the screen \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
-case $yn in
-[Yy]*)
-    clear
-    bash modules/funtion.sh
-    ;;
-[Nn]*) bash modules/funtion.sh ;;
-*) bash modules/funtion.sh ;;
-esac
+
+# if [ "$total_dev" == "0" ]; then
+#     echo -e "\e[91;1mNO DEVICE CONNECTED"
+# else
+#     if [ "$total_dev" == "1" ]; then
+
+#         dev_1_uninst
+
+#     else
+#         if [ "$total_dev" == "2" ]; then
+#             echo -e "\e[93mSelect the device to Uninstall 'apk' :- \e[92m\n"
+#             echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
+#             echo -e "\e[93m2. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
+#             while [ 1 ]; do
+#                 read -p $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
+#                 case $options in
+#                 "1")
+#                     dev_1_uninst
+#                     break
+#                     ;;
+#                 "2")
+#                     dev_2_uninst
+#                     break
+#                     ;;
+#                 *) echo -e "\n\e[1;4;91mENTER THE RIGHT OPTION BRO :- (1/2)\n" ;;
+#                 esac
+#             done
+#         else
+#             if [ "$total_dev" == "3" ]; then
+#                 echo -e "\e[93mSelect the device to Uninstall 'apk' :- \e[92m\n"
+#                 echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
+#                 echo -e "\e[93m1. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
+#                 echo -e "\e[93m1. \e[92m$dev_3 , \e[93mModel : \e[92m$mod_3"
+#                 while [ 1 ]; do
+#                     read -p $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
+#                     case $options in
+#                     "1")
+#                         dev_1_uninst
+#                         break
+#                         ;;
+#                     "2")
+#                         dev_2_uninst
+#                         break
+#                         ;;
+#                     "3")
+#                         dev_3_uninst
+#                         break
+#                         ;;
+#                     *) echo -e "\n\e[1;4;91mENTER THE RIGHT OPTION BRO :- (1/2/3/)\n" ;;
+#                     esac
+#                 done
+#             fi
+#         fi
+
+#     fi
+# fi
+
+## Asking to Clear the screen
+bash modules/HelperFunctions/AskClear
